### ISSUE TITLE
err - Expecting template to have 'from' attribute

### ISSUE THREAD

**Issue by maggienj** [maggienj/ActiveData#7]
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "setop.py:191" (extract_rows) - Timer start: call to ES
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "setop.py:193" (extract_rows) - Timer end  : call to ES (took 0 seconds)
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "query.py:74" (query) - Timer end  : translate (took 14.710 seconds)
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "query.py:74" (query) - Timer end  : total duration (took 15.961 seconds)
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "query.py:168" (_send_error) - WARNING: Could not process
{"meta": {"testing": true}, "from": "testing_000_f", "select": "_id", "format": "cube"}
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\query.py", line 168, in _send_error
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\query.py", line 112, in query
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\__init__.py", line 54, in output
	File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
	File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 197, in execute
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 267, in handle_one_request
	File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 232, in handle
	File "C:\Python27\lib\SocketServer.py", line 652, in __init__
	File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
	File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
	File "C:\Python27\lib\threading.py", line 754, in run
	File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
	File "C:\Python27\lib\threading.py", line 774, in __bootstrap
caused by
	ERROR: Expecting template to have 'from' attribute
	File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\strings.py", line 404, in _expand
	File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\strings.py", line 64, in expand_template
	File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\exceptions.py", line 90, in message
	File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\exceptions.py", line 94, in __contains__
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx_usingES.py", line 167, in query
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx.py", line 67, in run
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\query.py", line 74, in query
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\__init__.py", line 54, in output
	File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
	File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 197, in execute
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 267, in handle_one_request
	File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 232, in handle
	File "C:\Python27\lib\SocketServer.py", line 652, in __init__
	File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
	File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
	File "C:\Python27\lib\threading.py", line 754, in run
	File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
	File "C:\Python27\lib\threading.py", line 774, in __bootstrap

**Comment by maggienj** [comment]
kabalidaa (pid 8976) - 2017-05-25 20:11:05 - Main Thread - "query.py:168" (_send_error) - WARNING: Could not process
{"meta": {"testing": true}, "from": "testing_000_f", "select": "_id", "format": "cube"}

it has the "from" .... 
should it be from "0" ?

**Comment by maggienj** [comment]
not sure what is wrong with this query ...

{"meta": {"testing": true}, "from": "testing_000_f", "select": "_id", "format": "cube"}

will check... "query.py:168"

**Comment by klahnakoski** [comment]
ERROR: Expecting template to have 'from' attribute
    File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\strings.py", line 404, in expand

Indicates there is no problem with the query: There is a problem with how `Log.note()` or `Log.error()` is called.

**Comment by klahnakoski** [comment]
Specifically,

https://github.com/maggienj/ActiveData/blob/es5/pyLibrary/queries/es14/setop.py#L192

the first parameter must be a string

**Comment by klahnakoski** [comment]
I pushed changes to master that will complain more specifically about calling the logging library wrong.

**Comment by maggienj** [comment]
Tried to merge the changes from upstream master to es5 .....  



2017-05-25 20:46:25 - 
http://localhost:9200/testing_000_a20170525_204622/_flush:
	{"forced": false, "wait_if_ongoing": true}
2017-05-25 20:46:25 - PUT http://localhost:9200/testing_000_a20170525_204622/_flush
2017-05-25 20:46:25 - response: {"_shards":{"total":3,"successful":3,"failed":0}}
Error
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Users\user\PycharmProjects\ActiveData\tests\test_jx\test_set_ops.py", line 324, in test_id_select
    self.utils.execute_es_tests(test)
  File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 150, in execute_es_tests
    self.send_queries(subtest)
  File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 226, in send_queries
    Log.error("Failed test {{name|quote}}", {"name": subtest.name}, e)
  File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\__init__.py", line 392, in error
    raise e
Except: ERROR: Failed test "test_id_select"
	File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 226, in send_queries
	File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 150, in execute_es_tests
	File "C:\Users\user\PycharmProjects\ActiveData\tests\test_jx\test_set_ops.py", line 324, in test_id_select
	File "C:\Python27\lib\unittest\case.py", line 329, in run
	File "C:\Python27\lib\unittest\case.py", line 393, in __call__
	File "C:\Python27\lib\unittest\suite.py", line 108, in run
	File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
	File "C:\Python27\lib\unittest\suite.py", line 108, in run
	File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
	File "C:\Python27\lib\unittest\runner.py", line 151, in run
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pycharm\teamcity\unittestpy.py", line 207, in run
	File "C:\Python27\lib\unittest\main.py", line 232, in runTests
	File "C:\Python27\lib\unittest\main.py", line 95, in __init__
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pycharm\_jb_unittest_runner.py", line 29, in <module>
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1015, in run
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1578, in <module>
caused by
	ERROR: Failed request
	File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 377, in error
	File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 215, in send_queries
	File "C:\Users\user\PycharmProjects\ActiveData\tests\__init__.py", line 150, in execute_es_tests
	File "C:\Users\user\PycharmProjects\ActiveData\tests\test_jx\test_set_ops.py", line 324, in test_id_select
	File "C:\Python27\lib\unittest\case.py", line 329, in run
	File "C:\Python27\lib\unittest\case.py", line 393, in __call__
	File "C:\Python27\lib\unittest\suite.py", line 108, in run
	File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
	File "C:\Python27\lib\unittest\suite.py", line 108, in run
	File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
	File "C:\Python27\lib\unittest\runner.py", line 151, in run
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pycharm\teamcity\unittestpy.py", line 207, in run
	File "C:\Python27\lib\unittest\main.py", line 232, in runTests
	File "C:\Python27\lib\unittest\main.py", line 95, in __init__
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pycharm\_jb_unittest_runner.py", line 29, in <module>
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1015, in run
	File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1578, in <module>
caused by
	ERROR: problem
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx_usingES.py", line 170, in query
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx.py", line 71, in run
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\jx.py", line 62, in jx_query
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\__init__.py", line 54, in output
	File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
	File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 197, in execute
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 267, in handle_one_request
	File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 232, in handle
	File "C:\Python27\lib\SocketServer.py", line 652, in __init__
	File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
	File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
	File "C:\Python27\lib\threading.py", line 754, in run
	File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
	File "C:\Python27\lib\threading.py", line 774, in __bootstrap
caused by
	ERROR: Log.error was expecting a unicode template
	File "C:\Users\user\PycharmProjects\ActiveData\mo_logs\__init__.py", line 376, in error
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es14\setop.py", line 192, in extract_rows
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es14\setop.py", line 63, in es_setop
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx_usingES.py", line 159, in query
	File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\jx.py", line 71, in run
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\actions\jx.py", line 62, in jx_query
	File "C:\Users\user\PycharmProjects\ActiveData\active_data\__init__.py", line 54, in output
	File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
	File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
	File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 197, in execute
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 267, in handle_one_request
	File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
	File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 232, in handle
	File "C:\Python27\lib\SocketServer.py", line 652, in __init__
	File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
	File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
	File "C:\Python27\lib\threading.py", line 754, in run
	File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
	File "C:\Python27\lib\threading.py", line 774, in __bootstrap


2017-05-25 20:46:27 - Deleting index testing_000_a20170525_204622
2017-05-25 20:46:27 - GET http://localhost:9200/_aliases
2017-05-25 20:46:27 - response: {"saved_queries20170524_113002":{"aliases":{"saved_queries"...<snip>...ing_000_a20170525_204622":{"aliases":{"testing_000_a":{}}}}
2017-05-25 20:46:27 - 
http://localhost:9200/_aliases:
	{"actions": [{"remove": {"index": "testing_000_a20170525_204622", "alias": "testing_000_a"}}]}
2017-05-25 20:46:27 - PUT http://localhost:9200/_aliases
2017-05-25 20:46:27 - response: {"acknowledged":true}
2017-05-25 20:46:27 - delete response {"acknowledged": true} 
 
 
 
 
 
     


Ran 1 test in 6.012s

FAILED (errors=1)

Process finished with exit code 1

**Comment by klahnakoski** [comment]
Perfect!  The error in the code is shown:

    caused by
    ERROR: Log.error was expecting a unicode template
    File "C:\Users\user\PycharmProjects\ActiveData\mo_logs_init.py", line 376, in error
    File "C:\Users\user\PycharmProjects\ActiveData\pyLibrary\queries\es14\setop.py", line 192, in extract_rows
